project: "SAC-RND"
group: "sac-rnd-walker2d-medium-expert-v2-predictorsweep-v0"
name: "sac-rnd"
num_epochs: 3000
dataset_name: "walker2d-medium-expert-v2"

rnd_update_epochs: 1
rnd_switch_features: true
rnd_mlp_type: "concat_first"
rnd_target_mlp_type: "film_last"

critic_layernorm: true
batch_size: 1024
critic_learning_rate: 0.001
actor_learning_rate: 0.001
alpha_learning_rate: 0.001