project: "SAC-RND"
group: "sac-rnd-naive-hopper-medium-expert-v2-betasweep-v0"
name: "sac-rnd"
num_epochs: 3000
dataset_name: "hopper-medium-expert-v2"

rnd_update_epochs: 1
rnd_switch_features: false
rnd_mlp_type: "concat_first"
rnd_target_mlp_type: "concat_first"

critic_layernorm: true
batch_size: 1024
critic_learning_rate: 0.001
actor_learning_rate: 0.001
alpha_learning_rate: 0.001