entity: tlab
project: SAC-RND
program: offline_sac/algorithms/sac_rnd_betas.py
method: grid
parameters:
  config_path:
    values: [
#      "configs/sac-rnd/antmaze/antmaze_umaze_diverse.yaml",
#      "configs/sac-rnd/antmaze/antmaze_medium_diverse.yaml",
#      "configs/sac-rnd/antmaze/antmaze_large_diverse.yaml",
      "configs/sac-rnd/antmaze/antmaze_umaze.yaml",
      "configs/sac-rnd/antmaze/antmaze_medium_play.yaml",
      "configs/sac-rnd/antmaze/antmaze_large_play.yaml",
    ]
  train_seed:
    values: [0, 1, 2, 3]
  actor_beta:
    values: [0.5, 1.0, 1.5]
  critic_beta:
    values: [0.001, 0.01, 0.05, 0.1]